name: GI Project Build

on:
  push:
    branches: [main]
    paths: ["MarchSeven/**"]
  pull_request:
    branches: [main]
    paths: ["MarchSeven/**"]

jobs:
  build-gi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore MarchSeven/MarchSeven.csproj

      - name: Build GI project
        run: dotnet build MarchSeven/MarchSeven.csproj --no-restore --configuration Release
